# Generated by Django 5.2.7 on 2025-10-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyzedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("hash", models.CharField(max_length=128, verbose_name="Хэш")),
                ("payload", models.JSONField(verbose_name="Готовые данные")),
            ],
            options={
                "db_table": "emotion_analyzer",
                "default_permissions": (),
            },
        ),
    ]
